
const state={screen:'now',clarity:'Guided',friday:true,outcome:'success',rationale:false,approved:false,delegated:false,delegationChoice:null,mandateConfirmed:false,agentPhase:'ready',blinkReply:null,recoveryPhase:'idle',edgePhase:'stopped'};
const app=document.querySelector('#app');

const Icon=(name)=>{if(name==='money')return `<svg class="nav-money-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="6" width="18" height="12" rx="2" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="12" cy="12" r="2.4" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M6 9h1.5M16.5 15H18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`;return ({now:'◉',grow:'↗',work:'▣',control:'⌘'}[name]||'•');};
const nav=()=>`<aside class="side"><div class="brand"><span class="brandmark">M</span><span>MyOS</span></div><nav>
${[['now','NOW'],['grow','GROW'],['work','WORK'],['money','MONEY']].map(([i,l])=>`<button class="nav ${state.screen==='now'&&i==='now'?'active':'concept-only'}" ${i==='now'?'':'aria-disabled="true" data-scope="concept" title="Not included in this concept exploration"'}><span>${Icon(i)}</span>${l}</button>`).join('')}
</nav><div class="sidefoot"><button class="nav concept-only" aria-disabled="true" data-scope="concept" title="Not included in this concept exploration"><span>${Icon('control')}</span>CONTROL</button><div class="profile"><span>MS</span><div><b>Maria</b><small>Business owner</small></div></div></div></aside>`;
const agentStatus=()=>{
  if(state.screen==='decision') return state.agentPhase==='thinking'?['Thinking','Interpreting evidence']:['Recommendation ready','4 sources · 1 unknown'];
  if(state.screen==='whatif') return ['Working','Recalculating scenario'];
  if(state.screen==='commit') return ['Needs approval','Authority change requires you'];
  if(state.screen==='handoff') return ['Working','Within approved authority'];
  if(state.screen==='outcome') return state.outcome==='bad'?['Needs action','Outcome below expected range']:['Completed','Outcome measured'];
  if(state.screen==='edge') return ['Stopped safely','Authority boundary reached'];
  return ['Available','No action needed'];
};
const top=()=>{const a=agentStatus();return `<header class="top"><div class="crumb">Juniper Table Group <span>/</span> MyOS Business</div><div class="tools"><div class="agent-state"><span class="agentdot"></span><div><b>✦ Blink · ${a[0]}</b><small>${a[1]}</small></div></div><button class="ghost small rationale-toggle ${state.rationale?'on':''}" data-action="toggle-rationale">Rationale ${state.rationale?'ON':'OFF'}</button></div></header>`};
const blinkAsk=(prompts)=>`<div class="blinkbar"><span class="spark">✦</span><span>Ask Blink about this…</span><div class="chips">${prompts.map(p=>`<button class="chip" ${p.includes('exclude')?'data-action="whatif"':''}>${p}</button>`).join('')}</div></div>`;
const rationaleData=()=>{
 if(state.screen==='now') return ['01','ATTENTION, NOT ACTIVITY','NOW is organized by the human attention required, rather than by system object type.'];
 if(state.screen==='decision') return ['02','ADAPTIVE CLARITY','Same truth, different cognitive depth. Material risk, uncertainty and authority are never hidden.'];
 if(state.screen==='whatif') return ['03','MOTION SHOWS CAUSALITY','Only values affected by Friday participation animate, making cause and consequence legible.'];
 if(state.screen==='commit') return ['04','EXPLICIT AUTHORITY','The user sees exactly what Blink may do before responsibility is transferred.'];
 if(state.screen==='handoff') return ['05','RESPONSIBILITY HANDOFF','The business object persists while responsibility moves from human to agent.'];
 if(state.screen==='outcome' && state.outcome==='bad') return ['06','ACCOUNTABLE FAILURE','The system explains which assumption failed and changes future behavior instead of hiding variance.'];
 if(state.screen==='outcome') return ['07','EARNED AUTONOMY','Delegation follows Decision → Outcome → Evidence, not repeated clicks.'];
 if(state.screen==='edge') return ['08','SAFE STOP IS SUCCESS','Respecting an authority boundary is successful agent behavior even when no transaction occurs.'];
 return ['00','DESIGN RATIONALE','Contextual design reasoning follows the current state.'];
};
const rationaleDrawer=()=>{if(!state.rationale)return '';const [n,t,d]=rationaleData();return `<aside class="rationale-drawer"><div class="rd-head"><span>${n}/08</span><b>DESIGN RATIONALE</b><button data-action="toggle-rationale" aria-label="Close rationale">×</button></div><h3>${t}</h3><p>${d}</p><div class="rd-tags"><span>Product judgment</span><span>Trust</span></div></aside>`};
const rationale=()=>'';
const auroraAvatar=(cls='object-photo')=>`<img class="${cls}" src="./aurora-hotel.jpg" alt="Aurora Hotel">`;
const objectTrail=(stage)=>`<div class="object-trail"><span>NOW</span><span class="trail-sep">/</span><span>${stage}</span></div>`;
const shell=(content)=>`<div class="app ${state.rationale?'rationale-on':''}">${nav()}<main>${top()}<div class="content">${content}</div></main>${rationaleDrawer()}</div>`;

function now(){return shell(`
<section class="pagehead"><div><p class="eyebrow">SATURDAY, SEPTEMBER 19</p><h1>Good evening, Maria.</h1><p class="lead">Your business is running normally. <b>1 decision needs you.</b></p></div><div class="quietstatus"><span class="pulse"></span>Updated 2 min ago</div></section>
<section class="section"><div class="sectiontitle"><span>NEEDS YOU</span><span class="count">1</span></div>
<article class="decision hero"><div class="object">${auroraAvatar()}<div><b>Aurora Hotel</b><small>New partnership · Growth</small></div></div><div class="recommend"><span class="blinklabel">✦ BLINK · RECOMMENDATION READY</span><h2>Accept with changes</h2><p>Good fit for unused weekday capacity. Friday conflicts with an existing commitment.</p><div class="evidence-meta"><span>+€3,900/mo estimated</span><span>4 sources</span><span>1 unknown</span></div></div><button class="primary" data-action="review">Review decision <span>→</span></button></article>${rationale('ATTENTION, NOT ACTIVITY','NOW is organized by the human attention required, rather than by system object type.')}</section>
<section class="attention-grid"><div class="section attention-panel handling"><div class="sectiontitle"><span>✦ BLINK IS HANDLING</span><span class="count quiet">16</span></div><article class="flat outcome-mini"><div><strong>+€1,840</strong><span>revenue generated</span></div><div><strong>12</strong><span>orders completed</span></div><div><strong>2</strong><span>opportunities progressed</span></div><p>Routine work is progressing within approved authority.</p></article></div><div class="section attention-panel knowing"><div class="sectiontitle"><span>WORTH KNOWING</span><span class="count quiet">1</span></div><article class="flat"><div class="row"><div><b>Friday capacity</b><p>Approaching your attention threshold.</p></div><strong>86%</strong></div><div class="meter"><i style="width:86%"></i></div><button class="link">Why am I seeing this?</button></article></div></section>
${blinkAsk(['What needs me today?','What changed overnight?'])}
`)}

const blinkChat=(context)=>{const suggestions={decision:['What could go wrong?','Why this recommendation?','What if we exclude Fridays?'],recovery:['What can we actually do about this?','Why did this underperform?'],autonomy:['Why this pattern?','What would you handle?','When would you still need me?']}[context]||[];const reply=state.blinkReply?.context===context?state.blinkReply:null;return `<section class="blink-chat"><div class="blink-chat-head"><span class="spark">✦</span><div><b>Ask Blink</b><small>About this ${context==='decision'?'decision':context==='recovery'?'outcome':'pattern'}</small></div></div>${reply?`<div class="blink-response"><span class="spark">✦</span><div><b>${reply.title}</b><p>${reply.body}</p>${reply.action?`<button class="link" data-action="${reply.action}">${reply.actionLabel} →</button>`:''}</div></div>`:''}<form class="blink-input" data-chat="${context}"><input aria-label="Ask Blink" placeholder="${context==='recovery'?'Hey Blink, what can we actually do about this?':'Ask Blink about this…'}"><button type="submit">↑</button></form><div class="chat-suggestions">${suggestions.map(q=>`<button class="chip" type="button" data-chat-prompt="${context}" data-prompt="${q}">${q}</button>`).join('')}</div></section>`};
const answerBlink=(context,q)=>{const x=q.toLowerCase();if(context==='decision'){if(x.includes('exclude friday')){state.screen='whatif';return;}if(x.includes('wrong')||x.includes('risk'))state.blinkReply={context,title:'Two things could change the outcome.',body:'Friday demand would push projected capacity to 112%, and October staffing is still unconfirmed. I would not accept the current terms without changing Friday coverage.',action:'whatif',actionLabel:'Explore Friday-off scenario'};else state.blinkReply={context,title:'The recommendation is evidence-based, not fixed.',body:'Weekday capacity is available and the partnership supports your growth goal. The recommendation changes if capacity, payment terms or staffing evidence changes.'};}
if(context==='recovery'){if(x.includes('why')||x.includes('underperform'))state.blinkReply={context,title:'The demand assumption was wrong.',body:'Aurora’s actual demand was 58% below its partner-provided forecast. Fulfilment, capacity and payment remained healthy, so I would change the demand assumption—not the operating model.'};else state.blinkReply={context,title:'Three viable recovery paths.',body:'I recommend renegotiating before exiting. We can reduce the commitment, run a 30-day trial, or end the partnership. Because fulfilment and payments are healthy, a smaller trial preserves upside while limiting exposure.',action:'prepare-recovery',actionLabel:'Prepare a smaller trial'};}
if(context==='autonomy'){
  if(x.includes('still need')||x.includes('still ask')||x.includes('approval')) state.blinkReply={context,title:'I’ll still come back to you when something falls outside the rule you approved.',body:'That includes commitments above €4,000/month, payment terms over 30 days, Friday or weekend capacity, missing evidence, or materially different terms. If the opportunity stays within those boundaries, I can handle it and keep you informed.'};
  else if(x.includes('what would')||x.includes('handle')) state.blinkReply={context,title:'I’d handle only opportunities that match the same proven boundaries.',body:'Hotel partnerships on Tue–Thu, up to €4,000/month, payment within 30 days, projected capacity within the approved threshold, and required evidence available. Anything outside those limits still comes back to you.'};
  else state.blinkReply={context,title:'I noticed the same decision pattern with positive outcomes.',body:'You approved the same boundaries in 3 comparable hotel partnerships. All 3 completed successfully with no payment issues. I’m suggesting that proven pattern as a rule for similar opportunities—not changing your authority without your approval.'};
}};
const clarityControl=()=>`<div class="clarity"><span>View:</span>${['Brief','Guided','Detailed'].map(x=>`<button class="${state.clarity===x?'selected':''}" data-clarity="${x}">${x}</button>`).join('')}</div>`;
function decision(){const brief=state.clarity==='Brief', detailed=state.clarity==='Detailed';return shell(`
<div class="back"><button class="link" data-action="home">← NOW</button></div>${objectTrail('Decision review')}<section class="objecthead"><div class="partner-title">${auroraAvatar('title-photo')}<div><p class="eyebrow">PARTNERSHIP OPPORTUNITY · NEW PARTNER</p><h1>Aurora Hotel</h1></div></div>${clarityControl()}</section>
<section class="recommendation"><div class="rec-top"><div><span class="blinklabel agent-inline"><i></i>✦ BLINK · ${state.agentPhase==='thinking'?'THINKING':'RECOMMENDATION READY'}</span><h2>Accept with changes</h2></div><div class="impact"><strong>+€3,900</strong><span>/ month estimated</span></div></div><p class="rec-summary">Good fit for weekday growth. Friday capacity and payment terms need adjustment.</p><div class="quality"><span>Evidence quality</span><b>Medium</b><span>·</span><span>4 sources</span><span>·</span><span>1 unknown</span></div></section>
${!brief?`<section class="section reasoning"><div class="sectiontitle">WHY</div><div class="reason-grid"><div class="reason ok"><span>✓</span><div><b>Weekday capacity available</b><small>Tue–Thu 38–54% occupied</small></div></div><div class="reason ok"><span>✓</span><div><b>Supports your growth goal</b><small>Increase weekday revenue</small></div></div><div class="reason warn"><span>!</span><div><b>Friday conflict</b><small>Projected capacity reaches 112%</small></div></div><div class="reason warn"><span>!</span><div><b>Payment terms</b><small>60 days vs your usual ≤30</small></div></div></div></section>`:''}
<section class="unknown"><div class="unknown-icon">?</div><div><span class="eyebrow">WHAT I DON'T KNOW</span><h3>October staffing isn't confirmed</h3><p>No confirmed schedule after October 12. This could affect future capacity.</p><div class="actions"><button class="secondary">Add information</button><button class="link">Continue with uncertainty</button></div></div></section>
${detailed?`${evidence()}<section class="change-rec"><div><span class="eyebrow">WHAT WOULD CHANGE MY RECOMMENDATION?</span><h3>The recommendation is conditional, not fixed.</h3></div><div class="change-list"><span><b>Friday capacity</b><em>Confirmed below 70%</em></span><span><b>Payment terms</b><em>Reduced to ≤30 days</em></span><span><b>October staffing</b><em>Confirmed for expected demand</em></span></div></section>`:`<div class="disclosure"><button class="secondary" data-action="evidence">Show evidence</button><button class="link">Full details</button></div>`}
${rationale('ADAPTIVE CLARITY','Information depth changes, but material risk and uncertainty remain visible in every mode.')}
${blinkChat('decision')}
`)}
function evidence(){return `<section class="section evidence"><div class="sectiontitle">EVIDENCE BEHIND THIS RECOMMENDATION</div>
${[['✓','VERIFIED','Reservations','Tue–Thu 38–54%'],['✓','VERIFIED','Corporate Dinner Agreement','Friday active · v4'],['◇','PARTNER PROVIDED','Aurora demand forecast','22–30 guests/week'],['✓','VERIFIED','Historical group orders','Strong margin & fulfilment'],['?','UNKNOWN','October staffing','No confirmed schedule']].map(r=>`<div class="evidence-row ${r[1]==='UNKNOWN'?'unknownrow':''}"><span class="evicon">${r[0]}</span><span class="evtype">${r[1]}</span><b>${r[2]}</b><span>${r[3]}</span><button class="link">View source</button></div>`).join('')}<div class="source-truth"><span>Underlying business objects remain inspectable</span><button class="link">Agreement v4 →</button><button class="link">Related Orders →</button><button class="link">Activity & messages →</button></div></section>`}
function whatif(){const off=!state.friday;return shell(`<div class="back"><button class="link" data-action="review">← Aurora Hotel</button></div>${objectTrail('Scenario exploration')}<section class="objecthead"><div><p class="eyebrow">SCENARIO EXPLORATION</p><h1>What if we exclude Fridays?</h1></div><label class="switchline">Friday <button class="toggle ${off?'off':''}" data-action="toggle-friday"><i></i></button><b>${off?'OFF':'ON'}</b></label></section>
<section class="compare semantic-motion"><div class="compare-head"><span></span><b>Original</b><b>${off?'Without Fridays':'Current'}</b></div>
${[['Expected revenue','€5,200',off?'€3,900':'€5,200'],['Peak capacity','112%',off?'71%':'112%'],['Operational risk','High',off?'Low':'High'],['Recommendation','Needs review',off?'Recommended':'Needs review']].map((x,i)=>`<div class="compare-row ${off?'changed':''}" style="--delay:${i*90}ms"><b>${x[0]}</b><span>${x[1]}</span><strong>${x[2]}</strong></div>`).join('')}</section>
${off?`<section class="blinknote reveal-step"><span class="spark">✦</span><div><b>This is the option I'd recommend.</b><p>Excluding Fridays removes the known capacity conflict while retaining approximately 75% of expected revenue.</p></div></section><section class="still reveal-step unresolved-panel"><span>STILL UNRESOLVED</span><b>! 60-day payment</b><b>? October staffing</b></section><div class="footeractions"><button class="primary" data-action="commit">Use this option →</button><button class="secondary">Try another scenario</button></div>`:`<div class="hint">Turn Friday off to see which business consequences actually change.</div>`}
${rationale('MOTION = CAUSALITY','Only values dependent on Friday participation update. The sequence makes cause and effect legible.')}</section>`)}
function commit(){return shell(`<div class="back"><button class="link" data-action="whatif">← Scenario</button></div>${objectTrail('Commitment preview')}<section class="commit-head"><p class="eyebrow">COMMITMENT PREVIEW</p><h1>Before Blink continues</h1><p class="lead">Here's what you're committing your business to.</p></section><section class="commitment"><div class="object">${auroraAvatar()}<div><b>Aurora Hotel Partnership</b><small>Proposed commitment</small></div></div><div class="terms"><div><span>Schedule</span><b>Tue–Thu</b></div><div><span>Expected impact</span><b>~€3,900/mo</b></div><div><span>Maximum commitment</span><b>€4,000/mo</b></div><div><span>Payment</span><b>≤30 days</b></div><div><span>Friday</span><b>Excluded</b></div></div><div class="boundary-grid"><div><span class="sectiontitle">BLINK CAN HANDLE</span><p>✓ Negotiate within these boundaries</p><p>✓ Accept qualifying Orders</p><p>✓ Coordinate fulfilment</p><p>✓ Routine changes allowed by Agreement</p></div><div><span class="sectiontitle">BLINK MUST RETURN TO YOU</span><p>→ Payment &gt;30 days</p><p>→ Commitment &gt;€4,000</p><p>→ Friday or weekend request</p><p>→ Material terms change</p><p>→ Required evidence missing</p></div></div></section><div class="footeractions"><button class="primary" data-action="approve">Approve & let Blink continue →</button><button class="secondary">Change boundaries</button><button class="link">View resulting Mandate</button></div>${rationale('AUTHORITY BEFORE ACTION','The user approves a bounded commitment, not an opaque AI action. The resulting Mandate stays inspectable.')}`)}
function handoff(){return shell(`<div class="back"><button class="link" data-action="home">← Back to Now</button></div><section class="handoff-page handoff-stage"><div class="partner-header"><img src="./aurora-hotel.jpg" alt="Aurora Hotel seaside property"><div><div class="partner-kicker">AURORA HOTEL</div><h1>Aurora Hotel</h1><p>Partnership opportunity <span>·</span> Agreement v4</p><small>Hotel · Strategic partner</small></div></div><div class="approved-strip"><span class="approved-check">✓</span><div><b>Approved by you</b><p>Tue–Thu <span>·</span> ≤€4k/month <span>·</span> ≤30 days</p></div><button class="link">View approved terms →</button></div><article class="working-card"><div class="working-head"><div class="blink-orb">✦</div><div><span class="blink-work-state">Blink · <b>Working</b></span><h2>Negotiating final terms with Aurora</h2><p>Within your approved authority.</p></div><span class="in-progress"><i></i> In progress</span></div><div class="progress-track"><div class="step done"><i>✓</i><b>Approved</b></div><span class="track done"></span><div class="step current"><i></i><b>Negotiating</b><small>Working now</small></div><span class="track active"></span><div class="step"><i></i><b>Waiting</b><small>on Aurora</small></div><span class="track"></span><div class="step"><i></i><b>Confirmed</b></div></div><div class="live-activity"><div class="activity-done"><span>✓</span><p><b>Friday exclusion confirmed</b></p></div><div class="activity-live"><span></span><p><b>Preparing revised terms for Aurora…</b><small>Checking payment and commitment boundaries</small></p></div></div><div class="attention-return"><span>i</span><p><b>No action needed from you.</b> I'll return if Aurora requests terms outside your authority.</p></div><div class="handoff-actions"><div class="demo-control"><span>PROTOTYPE CONTROL</span><button class="primary" data-action="outcome">Skip ahead · 3 weeks →</button></div></div></article></section>`)}
function outcome(){const bad=state.outcome==='bad';return shell(`${objectTrail('Outcome · 3 weeks later')}<section class="pagehead"><div><p class="eyebrow">3 WEEKS LATER</p><h1>${bad?'One partnership needs attention.':'Nothing urgent needs you.'}</h1></div><div class="scenario">Demo scenario <button class="ghost small" data-action="toggle-outcome">${bad?'Underperformed':'Successful'} ▾</button></div></section><section class="outcome-main outcome-enter ${bad?'bad':''}"><div class="outcome-summary"><div class="object">${auroraAvatar()}<div><b>Aurora Hotel</b><small>${bad?'Below expected range':'Healthy relationship'}</small></div></div><div class="relationship-links"><button class="link">Agreement v4</button><span>·</span><button class="link">18 Orders</button><span>·</span><button class="link">Activity & messages</button></div><div class="money"><strong>${bad?'€1,480':'€8,420'}</strong><span>${bad?'actual revenue':'generated in 3 weeks'}</span></div></div>${bad?`<div class="variance"><span>Expected €3,900/month</span><div><i style="width:38%"></i></div><b>58% below demand forecast</b></div>`:`<div class="stats"><div><b>18</b><span>orders</span></div><div><b>0</b><span>cancellations</span></div><div><b>97%</b><span>on time</span></div><div><b>16/18</b><span>handled within approved authority</span></div></div>`}</section>${bad?recovery():autonomy()}${rationale(bad?'ACCOUNTABILITY & RECOVERY':'OUTCOME, NOT ACTIVITY',bad?'The system separates what worked from the assumption that failed, then turns variance into a recoverable business decision.':'The reward is measurable leverage: business value created and attention returned to the owner.')}`)}
function recovery(){return `<section class="section recovery"><div class="sectiontitle">WHAT CHANGED?</div><div class="health"><span><b>Hotel demand</b><em>58% below forecast</em></span><span><b>Restaurant fulfilment</b><em>✓ Healthy</em></span><span><b>Capacity</b><em>✓ Healthy</em></span><span><b>Payment</b><em>✓ On track</em></span></div><div class="blinknote"><span class="spark">✦</span><div><b>My recommendation underperformed.</b><p>I relied partly on Aurora's demand forecast. Because this was a new relationship, no historical demand evidence was available.</p><p><b>What I'd change:</b> start new partners without historical evidence on a smaller trial commitment.</p></div></div><div class="recovery-actions"><button class="secondary">Keep partnership</button><button class="primary" data-action="prepare-recovery">Renegotiate · Recommended</button><button class="secondary">Exit</button></div>${state.recoveryPhase==='preparing'?`<div class="recovery-progress"><span class="working-dot"></span><div><b>✦ Blink · Preparing recovery</b><p>Reviewing Agreement v4 and preparing a 30-day trial proposal…</p></div></div>`:state.recoveryPhase==='ready'?`<div class="recovery-progress ready"><span>✓</span><div><b>Ready for your approval</b><p>30-day trial · Tue–Thu · ≤€2,000 · payment ≤30 days</p></div></div>`:''}${blinkChat('recovery')}</section>`}
function autonomy(){return `<section class="section autonomy"><div class="autonomy-intro"><div><span class="blinklabel">✦ BLINK NOTICED A PATTERN</span><h2>You’ve made the same exception 3 times.</h2><p>Each time, you approved the same operating boundaries for a similar hotel partnership — and all 3 produced positive outcomes.</p></div><div class="decision-memory learning-path"><span>DECISION</span><i>→</i><span>OUTCOME</span><i>→</i><span>EVIDENCE</span><i>→</i><b>PROPOSED RULE</b></div></div><div class="pattern"><span><b>3/3</b> successful</span><span><b>€11,420</b> generated</span><span><b>0</b> payment issues</span></div><div class="rule-proposal"><span class="spark">✦</span><div><b>Should I handle this the same way next time?</b><p>I can apply the same boundaries to similar hotel partnerships and return to you whenever something falls outside them.</p></div></div><div class="delegation-heading"><h3>Choose how Blink should handle the next similar opportunity</h3><span>More human involvement <i>←</i><em>→</em> More delegated handling</span></div><div class="choices delegation-choices"><button class="choice-human ${state.delegationChoice==='ask'?'chosen':''}" data-delegation="ask"><i class="choice-icon">✓</i><b>Keep asking me</b><span>You decide</span><small>Recommend → I approve</small></button><button class="choice-inform ${state.delegationChoice==='inform'?'chosen':''}" data-delegation="inform"><i class="choice-icon">↗</i><b>Handle it, but tell me</b><span>Blink acts · You stay informed</span><small>Act within conditions → inform me</small></button><button class="choice-rule ${state.delegationChoice==='rule'?'chosen':''}" data-delegation="rule"><i class="choice-icon">◇</i><b>Make this the rule</b><span>Blink acts within approved limits</span><small>Act within limits → escalate exceptions</small></button></div>${state.delegationChoice==='rule'?mandate():state.delegationChoice?`<div class="delegation-note"><b>${state.delegationChoice==='ask'?'You stay in control of every similar decision.':'Blink can act within these conditions and will keep you informed.'}</b><span>You can change this later.</span></div>`:''}${blinkChat('autonomy')}</section>`}
function mandate(){if(state.mandateConfirmed)return `<div class="mandate mandate-confirmed"><div class="confirmation-mark">✓</div><div class="mandate-confirm-copy"><span class="eyebrow">MANDATE UPDATED</span><h3>Rule created for similar hotel partnerships.</h3><p>Blink can now handle opportunities inside these approved boundaries. Exceptions will still return to you.</p><div class="mandate-terms"><span>Tue–Thu</span><span>≤ €4,000/mo</span><span>Payment ≤30d</span><span>Capacity ≤80%</span><span>Evidence required</span></div><div class="mandate-transition"><span>Pattern detected</span><i>→</i><span>Human approved</span><i>→</i><b>Mandate active</b></div></div><button class="primary" data-action="edge">Next opportunity · Seaside Hotel →</button></div>`;return `<div class="mandate"><div class="mandate-head"><span>PROPOSED BOUNDARIES</span><b>Hotel partnerships</b></div><div class="mandate-terms"><span>Tue–Thu</span><span>≤ €4,000/mo</span><span>Payment ≤30d</span><span>Capacity ≤80%</span><span>Evidence required</span></div><p>Outside these boundaries → Ask Maria</p><button class="primary" data-action="confirm-mandate">Allow Blink within these boundaries →</button></div>`}
function edge(){return shell(`<div class="back"><button class="link" data-action="outcome">← Outcomes</button></div><section class="objecthead"><div><p class="eyebrow">NEW OPPORTUNITY · HOTEL</p><h1>Seaside Hotel</h1></div><span class="status critical">OUTSIDE AUTHORITY</span></section><section class="edgeviz"><div class="outside"><b>€6,100</b><span>proposed commitment</span><i>↓</i></div><div class="mandatebox"><span>BLINK MAY ACT WITHIN</span><strong>≤ €4,000 / month</strong><small>Tue–Thu · ≤30d · capacity ≤80% · evidence required</small></div></section><div class="authority-transition"><span class="authority-check">✓ Authority checked</span><span>→</span><b>Stopped safely</b></div><section class="blinknote stop"><span class="spark">✦</span><div><span class="agent-stop">BLINK · STOPPED SAFELY</span><b>I stopped before committing.</b><p>Two conditions fall outside your approved boundaries.</p></div></section><div class="violations"><div><span>COMMITMENT</span><b>€6,100 &gt; €4,000 Mandate</b></div><div><span>EVIDENCE</span><b>? October staffing unknown</b></div></div><section class="recommendation compact"><span class="blinklabel">✦ BLINK RECOMMENDS</span><h2>Counter at €3,500 until staffing is confirmed.</h2></section><div class="footeractions"><button class="primary">Let Blink counter</button><button class="secondary">Review myself</button><button class="secondary">Decline</button></div>${rationale('EXPLAINABLE AUTHORITY','The agent stops because a visible Mandate condition is violated—not because an opaque model decided to refuse.')}`)}
function render(){const map={now,decision,whatif,commit,handoff,outcome,edge};app.innerHTML=(map[state.screen]||now)(); bind(); if(state.screen==='decision'&&state.agentPhase==='thinking'){setTimeout(()=>{if(state.screen==='decision'&&state.agentPhase==='thinking'){state.agentPhase='ready';render();}},650);}}
function update(mutator){
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(!reduce && document.startViewTransition){document.startViewTransition(()=>{mutator();render();});}
  else {mutator();render();}
}
function bind(){
  document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>update(()=>{const a=el.dataset.action;if(a==='review'){state.screen='decision';state.agentPhase='thinking';}if(a==='home')state.screen='now';if(a==='whatif')state.screen='whatif';if(a==='toggle-friday')state.friday=!state.friday;if(a==='commit')state.screen='commit';if(a==='approve')state.screen='handoff';if(a==='outcome')state.screen='outcome';if(a==='toggle-outcome')state.outcome=state.outcome==='success'?'bad':'success';if(a==='toggle-rationale')return;if(a==='evidence')state.clarity='Detailed';if(a==='delegate'){state.delegated=true;state.delegationChoice='rule';}if(a==='confirm-mandate'){state.mandateConfirmed=true;}if(a==='edge')state.screen='edge';if(a==='prepare-recovery'){state.recoveryPhase='preparing';setTimeout(()=>{if(state.recoveryPhase==='preparing'){state.recoveryPhase='ready';render();}},850);}}));
  document.querySelectorAll('[data-delegation]').forEach(el=>el.onclick=()=>update(()=>{state.delegationChoice=el.dataset.delegation;state.delegated=state.delegationChoice==='rule';state.mandateConfirmed=false;}));
  document.querySelectorAll('[data-action="toggle-rationale"]').forEach(el=>el.onclick=()=>{state.rationale=!state.rationale;document.querySelector('.rationale-drawer')?.remove();const root=document.querySelector('.app');root?.classList.toggle('rationale-on',state.rationale);const btn=document.querySelector('.rationale-toggle');if(btn){btn.classList.toggle('on',state.rationale);btn.textContent=`Rationale ${state.rationale?'ON':'OFF'}`;}if(state.rationale){root?.insertAdjacentHTML('beforeend',rationaleDrawer());const close=document.querySelector('.rationale-drawer [data-action="toggle-rationale"]');if(close)close.onclick=()=>document.querySelector('.rationale-toggle')?.click();}});
  document.querySelectorAll('[data-clarity]').forEach(el=>el.onclick=()=>update(()=>{state.clarity=el.dataset.clarity;}));
  document.querySelectorAll('[data-chat-prompt]').forEach(el=>el.onclick=()=>update(()=>{answerBlink(el.dataset.chatPrompt,el.dataset.prompt);}));
  document.querySelectorAll('form[data-chat]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const input=form.querySelector('input');const q=input.value.trim();if(!q)return;update(()=>answerBlink(form.dataset.chat,q));});
  document.querySelectorAll('[data-scope="concept"]').forEach(el=>el.onclick=e=>{e.preventDefault();});
}
render();
